version: '2'
services:
  db:
    image: "postgres:${PGVERSION}"
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
  bootstrap:
    image: concourse-pgbootstrap
    links:
      - db
    environment:
      PGHOST: "${PGHOST}"
      PGPORT: "${PGPORT}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      CONCOURSE_DB: "${CONCOURSE_DB}"
      CONCOURSE_DB_PASSWORD: "${CONCOURSE_DB_PASSWORD}"
      CONCOURSE_DB_USER: "${CONCOURSE_DB_USER}"
  concourse-admin:
    image: concourse-admin
    depends_on:
      - bootstrap
      - db
    ports:
      - 8080:8080
      - 2222:2222
    environment:
      CONCOURSE_DB_HOST: "${PGHOST}"
      CONCOURSE_DB_PORT: "${PGPORT}"
      CONCOURSE_DB: "${CONCOURSE_DB}"
      CONCOURSE_DB_PASSWORD: "${CONCOURSE_DB_PASSWORD}"
      CONCOURSE_DB_USER: "${CONCOURSE_DB_USER}"
      CONCOURSE_URL: "${CONCOURSE_URL}"
    command: --development-mode
  concourse-worker:
    image: concourse-worker
    privileged: true
    depends_on:
      - concourse-admin
    links:
      - concourse-admin
    environment:
      CONCOURSE_TSA_HOST: concourse-admin
